server:
  port: 9091

spring:
  application:
    name: play-together-user-center
  datasource:
    username: root
    password: 990923*Dy
    url: jdbc:mysql://175.24.2.222:3306/play_together?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    username: pt
    password: pt
    virtual-host: /pt
    host: mbcwdl.space
  redis:
    host: mbcwdl.space
    password: defender

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.playtogether.usercenter
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.playtogether.usercenter.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10085/eureka