server:
  port: 8401

spring:
  application:
    name: play-together-auth-center
  redis:
    password: defender
    host: mbcwdl.space
  rabbitmq:
    host: mbcwdl.space
    username: pt
    password: pt
    virtual-host: /pt

pt:
  jwt:
    secret: pt@Login(Auth}*^31)&guanlibin%
    authCenterPublicKeyPath: /root/pt-temp/rsa/auth-center-rsa.pub
    authCenterPrivateKeyPath: /root/pt-temp/rsa/auth-center-rsa.pub
    microServicePublicKeyPath: /root/pt-temp/rsa/micro-service-rsa.pub
    microServicePrivateKeyPath: /root/pt-temp/rsa/micro-service-rsa.pri
    temporaryExpire: 1440
    permanentExpire: 525,600

qq:
  oauth:
    appId: 101915958
    appKey: 7f837c73f78a211ace6748752dc51603
    cbUrl: http://pt.mbcwdl.space/attach.html
    authorizationCodeUrl: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    accessTokenUrl: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openIdUrl: https://graph.qq.com/oauth2.0/me?access_token=%s
    userInfoUrl: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s

eureka:
  client:
    service-url:
      defaultZone: http://mbcwdl.space:10085/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 24000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
