spring:
  application:
    name: play-together-registry-center
server:
  port: 10085
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://mbcwdl.space:10085/eureka