server:
  port: 10001

spring:
  application:
    name: play-together-gateway
  redis:
    password: defender
    host: mbcwdl.space

zuul:
  prefix: /v
  routes:
    play-together-auth: /auth/**
    play-together-user: /user/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitive-headers:
  add-host-header: true

eureka:
  client:
    service-url:
      defaultZone: http://mbcwdl.space:10085/eureka
    registry-fetch-interval-seconds: 10

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 24000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000

pt:
  filter:
    auth:
      authCenterPublicKeyPath: /root/pt-temp/rsa/auth-center-rsa.pub
      authCenterPrivateKeyPath: /root/pt-temp/rsa/auth-center-rsa.pri
      microServicePublicKeyPath: /root/pt-temp/rsa/micro-service-rsa.pub
      microServicePrivateKeyPath: /root/pt-temp/rsa/micro-service-rsa.pri
        allowPath:
          - /v/auth/doc.html
          - /v/auth/swagger-resources
          - /v/auth/v2/api-docs
          - /v/auth/webjars
          - /v/auth/login
          - /v/auth/loginVerifyCode
          - /v/auth/qqLogin
          - /v/auth/qqLoginCallback
          - /v/auth/qqBinding
          - /v/user/doc.html
          - /v/user/swagger-resources
          - /v/user/v2/api-docs
          - /v/user/webjars
          - /v/user/register
          - /v/user/registerVerifyCode
          - /v/user/nickname/available
        forbiddenPath:
          - /v/user/count
          - /v/user/query/accountAndPassword
          - /v/user/uid/qqOpenId
          - /v/user/update