server:
  port: 10001

spring:
  application:
    name: play-together-gateway

zuul:
  prefix: /v/api
  routes:
    play-together-auth-center: /auth/**
    play-together-user-center: /user/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10085/eureka
    registry-fetch-interval-seconds: 10
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12500
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0