server:
  port: 10001

spring:
  application:
    name: play-together-gateway
  redis:
    password: defender
    host: mbcwdl.space

zuul:
  prefix: /v
  routes:
    play-together-auth-center: /auth/**
    play-together-user-center: /user/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitive-headers:
  add-host-header: true

pt:
  filter:
      auth:
        authCenterPublicKeyPath: D:/auth-center-rsa.pub
        authCenterPrivateKeyPath: D:/auth-center-rsa.pri
        microServicePublicKeyPath: D:/micro-service-rsa.pub
        microServicePrivateKeyPath: D:/micro-service-rsa.pri
        allowPath:
          - /v/auth/
          - /v/user/doc.html
          - /v/user/swagger-resources
          - /v/user/v2/api-docs
          - /v/user/webjars
          - /v/user/register
          - /v/registerVerifyCode
          - /v/nickname/available
        forbiddenPath:
          - /v/user/count
          - /v/user/uid/accountAndPassword
          - /v/user/uid/qqOpenId
          - /v/user/update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10085/eureka
    registry-fetch-interval-seconds: 10

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 24000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000